[package]
name = "crabtype"
version = "0.1.0"
edition = "2021"

[dependencies]
dict = "0.1.5"
rand = "0.8.5"
serde = "1.0.203"
serde_json = "1.0.117"
termios = "0.3.3"
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = "0.26.3"
